import { SettingHttpTcpModule as CountriesSettingHttpTcpModule } from './src/api/setting';
import { AccessAccessOptionHttpTcpModule as CountriesAccessAccessOptionHttpTcpModule } from './src/api/access-access-option';
import { AccessOptionHttpTcpModule as CountriesAccessOptionHttpTcpModule } from './src/api/access-option';
import { AccessStatusHttpTcpModule as CountriesAccessStatusHttpTcpModule } from './src/api/access-status';
import { AccessHttpTcpModule as CountriesAccessHttpTcpModule } from './src/api/access';
import { RoleAccessHttpTcpModule as CountriesRoleAccessHttpTcpModule } from './src/api/role-access';
import { RegionContentHttpTcpModule as CountriesRegionContentHttpTcpModule } from './src/api/region-content';
import { RegionRegionOptionHttpTcpModule as CountriesRegionRegionOptionHttpTcpModule } from './src/api/region-region-option';
import { RegionOptionHttpTcpModule as CountriesRegionOptionHttpTcpModule } from './src/api/region-option';
import { RegionStatusHttpTcpModule as CountriesRegionStatusHttpTcpModule } from './src/api/region-status';
import { RegionHttpTcpModule as CountriesRegionHttpTcpModule } from './src/api/region';
import { TypeTypeOptionHttpTcpModule as CountriesTypeTypeOptionHttpTcpModule } from './src/api/type-type-option';
import { TypeOptionHttpTcpModule as CountriesTypeOptionHttpTcpModule } from './src/api/type-option';
import { TypeStatusHttpTcpModule as CountriesTypeStatusHttpTcpModule } from './src/api/type-status';
import { TypeHttpTcpModule as CountriesTypeHttpTcpModule } from './src/api/type';

export CountriesAccessAccessOptionHttpTcpModule;
export CountriesAccessOptionHttpTcpModule;
export CountriesAccessStatusHttpTcpModule;
export CountriesAccessHttpTcpModule;
export CountriesRoleAccessHttpTcpModule;
export CountriesSettingHttpTcpModule;
export CountriesRegionContentHttpTcpModule;
export CountriesRegionRegionOptionHttpTcpModule;
export CountriesRegionOptionHttpTcpModule;
export CountriesRegionStatusHttpTcpModule;
export CountriesRegionHttpTcpModule;
export CountriesTypeTypeOptionHttpTcpModule;
export CountriesTypeOptionHttpTcpModule;
export CountriesTypeStatusHttpTcpModule;
export CountriesTypeHttpTcpModule;
